### ISSUE TITLE
Imagick issue

### ISSUE THREAD

**Issue by mmguide2003** [devisephp/bootstrap#2]
Using a Mac. On composer install:

 PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.8/lib/php/extensions/no-debug-non-zts-20131226/imagick' - dlopen(/usr/local/Cellar/php56/5.6.8/lib/php/extensions/no-debug-non-zts-20131226/imagick, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.8/lib/php/extensions/no-debug-non-zts-20131226/imagick' - dlopen(/usr/local/Cellar/php56/5.6.8/lib/php/extensions/no-debug-non-zts-20131226/imagick, 9): image not found in Unknown on line 0

Browser window has this message

/home/vagrant/projects/devise/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/vagrant/projects/devise/bootstrap/autoload.php on line 17

**Comment by dolbex** [comment]
Looks like you may not have imagemagick installed.

If you're on Homestead / Ubuntu:

```
sudo apt-get install imagemagick
sudo apt-get install php5-imagick
```

Let me know if that fixes this error and I'll close.

**Comment by mmguide2003** [comment]
Thanks I tried that but didn't work. However this did:

```
brew install php53-imagick
```

But after checking phphinfo.
Get this now:

```
Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.9/lib/php/extensions/no-debug-non-zts-20131226/imagick' - dlopen(/usr/local/Cellar/php56/5.6.9/lib/php/extensions/no-debug-non-zts-20131226/imagick, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.9/lib/php/extensions/no-debug-non-zts-20131226/imagick' - dlopen(/usr/local/Cellar/php56/5.6.9/lib/php/extensions/no-debug-non-zts-20131226/imagick, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.9/lib/php/extensions/no-debug-non-zts-20131226/imagick' - dlopen(/usr/local/Cellar/php56/5.6.9/lib/php/extensions/no-debug-non-zts-20131226/imagick, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.9/lib/php/extensions/no-debug-non-zts-20131226/imagick' - dlopen(/usr/local/Cellar/php56/5.6.9/lib/php/extensions/no-debug-non-zts-20131226/imagick, 9): image not found in Unknown on line 0
```

The App is now running though

**Comment by dolbex** [comment]
Hmm, I'm not sure on the imagemagick issue. I can tell you that my preference is to use Homestead for development. I always have a hard time with PHP on the base mac. Since that's really not directly related to the project I'm going to go ahead and close the issue.

**Comment by mmguide2003** [comment]
But I'm using Homestead.

```
 On Thursday, 4 June 2015, 14:35, Gary Williams <notifications@github.com> wrote:
```

 Closed #2.—

**Comment by dolbex** [comment]
@mmguide2003 - I don't understand. I stated to use:

```
sudo apt-get install imagemagick
sudo apt-get install php5-imagick
```

Which will work on Homestead (ubuntu). You then stated you used brew (which implies you're installing it to your mac. You need to install it to the homestead virtual machine. SSH into the vm with

```
ssh vagrant@127.0.0.1 -p 2222
```

Then try running the commands at the top of this comment.

**Comment by barryj** [comment]
I know this is an old issue, but if anybody comes across it and is trying to make Imagick work for PHP7 (specifically using a homestead/vagrant box) then this video gives a perfect runthrough, with explanations of each step so that you understand why you are doing them: https://www.youtube.com/watch?v=q3c6O85_LoA
