### ISSUE TITLE
Enabling User Registration

### ISSUE THREAD

**Issue by ghost** [devisephp/bootstrap#3]
Followed the steps here: http://devisephp.com/docs/users-groups/ to enable user registration, but visiting /admin/register leads to "InvalidArgumentException in FileViewFinder.php line 137: View [] not found." 

Looking at User Registration page settings shows no template is selected, and I can't find a template in the dropdown that I guess would be called Device Admin User Registration (or something similar). Testing with random template corrects the view, but obviously without the correct template - but I think it should be like the install template for the initial admin user, right?

**Comment by dolbex** [comment]
That's odd. Mine is working fine at:

/admin/register

It may be that it's protected by default. Try logging in and see if it loads. If it does and you want to reveal that then remove the before filter in settings for that page.

**Comment by ghost** [comment]
Logged in or not, same view error. What is the default template supposed to be?

**Comment by ghost** [comment]
Ok, I reinstalled the bootstrap to try again.

It works when I first go to /admin/register - after clicking "edit page" button from admin/pages/69/edit, without making any changes, the error returns. Couldn't remove ifNotLoggedInGoToLogin for testing as a result.

Again, the missing default template appears to be the issue.

**Comment by ghost** [comment]
OK:

With every save, the "view" column of "User Registration" of the "dvs_pages" table is getting overwritten from "devise::admin.users.register" to blank, but not null. 

This can manually be repaired after removing ifNotLoggedInGoToLogin, which allows public registration, but moving the register.blade.php file to /resources/views/templates and registering the new template also works to provide a dropdown option.

Another issue, however, is that users being deleted aren't removed from the database, just the app - so if a user tries to re-register with the same email, the app thinks they are a live user.

**Comment by billbostick** [comment]
Not sure why this issue was closed, but these problems still exist. If you follow the documented process to enable user registration, you will break the register route in the pages db table.

**Comment by barryj** [comment]
The register.blade.php is still not registered as a template by default. i haven't tried deleting a user so I do not know if this works
